# Build stage
FROM node:20-alpine AS builder

WORKDIR /app
COPY . .
RUN npm install --production=false
RUN npm run build

# Production stage
FROM node:20-alpine AS runner

WORKDIR /app

# Create a non-root user
COPY --from=builder /app ./
RUN chown -R node:node /app
USER node
RUN npm install --production
EXPOSE 3000
ENV HOST=0.0.0.0
CMD ["npm", "start"]